services:
  api:
    build: 
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - ./src/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      - ./src/logs:/app/logs:rw
      - ./src/uploads:/app/uploads:rw
      - /tmp:/app/temp:rw
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:${HTTP_PORT:-80}
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    volumes:
      - frontend-dist:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - frontend-dist:/usr/share/nginx/html:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_started
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      /bin/sh -c "
      if [ -f /etc/letsencrypt/live/fgtsagent.com.br/fullchain.pem ]; then
        echo 'Certificados SSL encontrados, iniciando nginx com SSL...'
      else
        echo 'Certificados SSL não encontrados, iniciando nginx sem SSL...'
      fi &&
      exec nginx -g 'daemon off;'
      "

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-var:
    driver: local
  nginx-cache:
    driver: local
  frontend-dist:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16