#!/bin/bash

echo "🔍 Verificando configuração de conta WhatsApp Business..."
echo "========================================================"

echo ""
echo "📋 Problema identificado:"
echo "========================="
echo "❌ Nenhuma conta WhatsApp Business encontrada"
echo ""
echo "🔍 Possíveis causas:"
echo "==================="
echo "1. Usuário não tem conta WhatsApp Business configurada"
echo "2. Usuário não completou o processo de Embedded Signup"
echo "3. Permissões insuficientes no Facebook App"
echo "4. Config ID não está configurado corretamente"
echo ""

echo "💡 Soluções:"
echo "============"
echo "1. Verificar se o usuário tem conta WhatsApp Business:"
echo "   - Acesse: https://business.facebook.com/wa/manage/accounts"
echo "   - Verifique se há contas WhatsApp Business listadas"
echo ""
echo "2. Se não há conta, criar uma:"
echo "   - Use o Embedded Signup da Meta"
echo "   - Ou configure manualmente no Meta Business Suite"
echo ""
echo "3. Verificar permissões do Facebook App:"
echo "   - whatsapp_business_management"
echo "   - whatsapp_business_messaging"
echo "   - business_management"
echo ""
echo "4. Verificar Config ID:"
echo "   - Config ID atual: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "   - Verificar se está configurado no Facebook Developer Console"
echo ""

echo "🔧 Configurações atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "📱 Próximos passos:"
echo "=================="
echo "1. Verificar se você tem conta WhatsApp Business"
echo "2. Se não tem, criar uma conta primeiro"
echo "3. Depois tentar conectar novamente"
echo "4. Se ainda não funcionar, verificar permissões"
echo ""

echo "🔗 Links úteis:"
echo "==============="
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"

