#!/bin/bash

echo "🔍 Investigação Detalhada do Fluxo Config ID..."
echo "=============================================="

echo ""
echo "📋 Configurações Atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "🎯 Problema Identificado:"
echo "========================="
echo "❌ Config ID deveria permitir seleção/criação de conta WhatsApp Business"
echo "❌ Mas estamos recebendo 'conta não encontrada'"
echo "❌ Isso indica que o fluxo não está funcionando corretamente"
echo ""

echo "🔍 Possíveis Causas:"
echo "==================="
echo "1. Config ID não está configurado corretamente no Facebook Developer Console"
echo "2. Config ID não está habilitado para Embedded Signup"
echo "3. Permissões insuficientes no Facebook App"
echo "4. Fluxo do Config ID não está sendo iniciado corretamente"
echo "5. Usuário não está completando o processo de Embedded Signup"
echo ""

echo "💡 Soluções para Investigar:"
echo "============================"
echo "1. Verificar configuração do Config ID no Facebook Developer Console:"
echo "   - Vá para: https://developers.facebook.com/"
echo "   - Seu App > Produtos > WhatsApp Business API"
echo "   - Configurações > Cadastro incorporado"
echo "   - Verificar se o Config ID está ativo"
echo ""
echo "2. Verificar se o Config ID está habilitado:"
echo "   - Config ID deve estar em 'Ativo' ou 'Habilitado'"
echo "   - Verificar se há restrições de domínio"
echo ""
echo "3. Testar fluxo manualmente:"
echo "   - Acessar: https://business.facebook.com/wa/manage/accounts"
echo "   - Verificar se consegue criar/gerenciar contas WhatsApp Business"
echo ""
echo "4. Verificar permissões do Facebook App:"
echo "   - whatsapp_business_management (OBRIGATÓRIO)"
echo "   - whatsapp_business_messaging (OBRIGATÓRIO)"
echo "   - business_management (OBRIGATÓRIO)"
echo ""

echo "🔧 Configurações Necessárias no Facebook Developer Console:"
echo "=========================================================="
echo "1. App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "2. Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "3. App Domains: localhost"
echo "4. Valid OAuth Redirect URIs: https://localhost:5173/"
echo "5. Produtos: WhatsApp Business API (ATIVO)"
echo "6. Configurações > Cadastro incorporado: HABILITADO"
echo ""

echo "📱 Para Testar o Fluxo:"
echo "======================"
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Observe se o processo de Embedded Signup aparece"
echo "5. Verifique se consegue selecionar/criar conta WhatsApp Business"
echo "6. Complete todo o processo"
echo ""

echo "🔍 Logs para Observar:"
echo "====================="
echo "1. No console do navegador:"
echo "   - Resposta completa do Facebook"
echo "   - Código de autorização recebido"
echo "   - Permissões concedidas"
echo ""
echo "2. No backend:"
echo "   - Troca de código por access token"
echo "   - Busca de dados do usuário"
echo "   - Tentativas de encontrar WhatsApp Business"
echo ""

echo "🚨 Se o problema persistir:"
echo "=========================="
echo "1. Verificar se o Facebook App está em modo de desenvolvimento"
echo "2. Adicionar usuário como testador no Facebook App"
echo "3. Verificar se há restrições de domínio no Config ID"
echo "4. Testar com um Config ID diferente"
echo "5. Verificar se o usuário tem permissões para criar contas WhatsApp Business"
echo ""

echo "🔗 Links Úteis:"
echo "=============="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"

