#!/bin/bash

echo "🔍 Investigando Campos da API de Números de Telefone da Meta..."
echo "============================================================="

echo ""
echo "❌ Erro Encontrado:"
echo "=================="
echo "Erro: (#100) Tried accessing nonexisting field (phone_number) on node type (WhatsAppBusinessPhoneNumber)"
echo "Problema: Campo 'phone_number' não existe no tipo WhatsAppBusinessPhoneNumber"
echo ""

echo "📚 Documentação da Meta - Campos Corretos:"
echo "=========================================="
echo "1. WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "2. Phone Numbers API: https://developers.facebook.com/docs/whatsapp/phone-numbers"
echo "3. Graph API Reference: https://developers.facebook.com/docs/graph-api/reference"
echo ""

echo "🎯 Campos Corretos para WhatsAppBusinessPhoneNumber:"
echo "=================================================="
echo "- id: ID único do número"
echo "- verified_name: Nome verificado"
echo "- quality_rating: Avaliação de qualidade"
echo "- code_verification_status: Status da verificação"
echo "- display_phone_number: Número de exibição"
echo "- name_status: Status do nome"
echo "- new_name_status: Status do novo nome"
echo ""

echo "⚠️  Campos que NÃO existem:"
echo "========================="
echo "- phone_number: ❌ Não existe neste endpoint"
echo "- number: ❌ Não existe neste endpoint"
echo ""

echo "💡 Correção Necessária:"
echo "======================"
echo "1. Remover 'phone_number' dos campos"
echo "2. Usar apenas campos válidos"
echo "3. O número já vem na lista de phone_numbers"
echo "4. Este endpoint é para detalhes, não para o número em si"
echo ""

echo "🔧 Implementação Corrigida:"
echo "=========================="
echo "fields=id,verified_name,quality_rating,code_verification_status,display_phone_number,name_status,new_name_status"
echo ""

echo "📋 Processo Correto:"
echo "==================="
echo "1. Buscar lista de números: /{wba-id}/phone_numbers"
echo "2. Selecionar número da lista (já tem phone_number)"
echo "3. Buscar detalhes: /{phone-id} (sem phone_number)"
echo "4. Combinar dados da lista + detalhes"
echo ""
