#!/bin/bash

echo "🔍 Pesquisando API de Detalhes de Número de Telefone da Meta..."
echo "============================================================="

echo ""
echo "📚 Documentação da Meta - Links Importantes:"
echo "============================================"
echo "1. WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "2. Phone Numbers API: https://developers.facebook.com/docs/whatsapp/phone-numbers"
echo "3. Graph API: https://developers.facebook.com/docs/graph-api"
echo "4. Phone Number Details: https://developers.facebook.com/docs/whatsapp/phone-numbers#get-phone-number"
echo ""

echo "🎯 Endpoints para Buscar Detalhes de Número:"
echo "==========================================="
echo "1. /{phone-number-id} - Buscar detalhes de um número específico"
echo "2. /{phone-number-id}?fields=id,phone_number,verified_name,quality_rating,code_verification_status,display_phone_number"
echo "3. /{phone-number-id}/verification_status - Status de verificação"
echo "4. /{phone-number-id}/quality_rating - Avaliação de qualidade"
echo ""

echo "🔍 Processo Correto:"
echo "==================="
echo "1. Ter o ID do número de telefone (phone_number_id)"
echo "2. Usar o endpoint: /{phone-number-id}"
echo "3. Buscar campos específicos: id, phone_number, verified_name, etc."
echo "4. Verificar status de verificação e qualidade"
echo ""

echo "💡 Exemplo de Implementação:"
echo "==========================="
echo "GET https://graph.facebook.com/v23.0/{phone-number-id}"
echo "Headers: Authorization: Bearer {access_token}"
echo "Fields: id,phone_number,verified_name,quality_rating,code_verification_status,display_phone_number"
echo ""

echo "📋 Campos Disponíveis:"
echo "====================="
echo "- id: ID único do número"
echo "- phone_number: Número de telefone"
echo "- verified_name: Nome verificado"
echo "- quality_rating: Avaliação de qualidade (GREEN, YELLOW, RED, UNKNOWN)"
echo "- code_verification_status: Status da verificação do código"
echo "- display_phone_number: Número de exibição"
echo "- name_status: Status do nome"
echo "- new_name_status: Status do novo nome"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Phone Numbers API: https://developers.facebook.com/docs/whatsapp/phone-numbers"
echo "Graph API: https://developers.facebook.com/docs/graph-api"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo ""

echo "💡 Próximos Passos:"
echo "=================="
echo "1. Implementar busca por detalhes do número"
echo "2. Usar o endpoint correto da Meta API"
echo "3. Tratar diferentes status de qualidade"
echo "4. Salvar detalhes completos no banco"
echo "5. Implementar verificação de status"
