#!/bin/bash

echo "🔍 Pesquisando Documentação da Meta - Config ID e Embedded Signup..."
echo "=================================================================="

echo ""
echo "📚 Documentação da Meta - Links Importantes:"
echo "============================================"
echo "1. Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo "2. WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "3. Facebook Login: https://developers.facebook.com/docs/facebook-login"
echo "4. Graph API: https://developers.facebook.com/docs/graph-api"
echo ""

echo "🎯 Processo Correto do Config ID:"
echo "================================"
echo "1. Usuário inicia Embedded Signup com Config ID"
echo "2. Facebook retorna código de autorização"
echo "3. Backend troca código por access token"
echo "4. Backend busca dados da conta WhatsApp Business"
echo ""

echo "🔍 Problema Identificado:"
echo "========================"
echo "❌ Estamos trocando o código por token corretamente"
echo "❌ Mas não estamos encontrando a conta WhatsApp Business"
echo "❌ Isso indica que o processo de Embedded Signup não foi completado"
echo ""

echo "💡 Possíveis Causas:"
echo "==================="
echo "1. Config ID não está configurado para criar contas WhatsApp Business"
echo "2. Usuário não completou o processo de Embedded Signup"
echo "3. Permissões insuficientes para criar contas WhatsApp Business"
echo "4. Facebook App em modo de desenvolvimento"
echo "5. Domínio não autorizado no Config ID"
echo ""

echo "🔧 Verificações Necessárias:"
echo "==========================="
echo "1. No Facebook Developer Console:"
echo "   - Config ID deve estar 'Ativo'"
echo "   - Domínio localhost deve estar autorizado"
echo "   - Permissões devem estar concedidas"
echo ""
echo "2. No processo de login:"
echo "   - Deve aparecer o processo de Embedded Signup"
echo "   - Deve permitir selecionar/criar conta WhatsApp Business"
echo "   - Deve ser completado com sucesso"
echo ""

echo "📱 Para Testar:"
echo "=============="
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Observe se aparece o processo de Embedded Signup"
echo "5. Verifique se consegue selecionar/criar conta WhatsApp Business"
echo "6. Complete todo o processo"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo ""

echo "💡 Próximos Passos:"
echo "=================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se o processo de Embedded Signup aparece"
echo "3. Verificar se o usuário consegue completar o processo"
echo "4. Se necessário, criar novo Config ID"
echo "5. Verificar se o Facebook App está configurado corretamente"

