#!/bin/bash

echo "🔍 Pesquisando API de Números de Telefone da Meta..."
echo "=================================================="

echo ""
echo "📚 Documentação da Meta - Links Importantes:"
echo "============================================"
echo "1. WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "2. Graph API: https://developers.facebook.com/docs/graph-api"
echo "3. Phone Numbers API: https://developers.facebook.com/docs/whatsapp/phone-numbers"
echo "4. Business Management API: https://developers.facebook.com/docs/business-management-api"
echo ""

echo "🎯 Endpoints para Buscar Números de Telefone:"
echo "============================================"
echo "1. /{whatsapp-business-account-id}/phone_numbers"
echo "2. /{page-id}/whatsapp_business_accounts"
echo "3. /{business-id}/whatsapp_business_accounts"
echo "4. /{ad-account-id}/whatsapp_business_accounts"
echo ""

echo "🔍 Processo Correto:"
echo "==================="
echo "1. Buscar WhatsApp Business Account ID"
echo "2. Usar o ID para buscar números de telefone"
echo "3. Endpoint: /{wba-id}/phone_numbers"
echo "4. Fields: id, phone_number, verified_name, quality_rating, etc."
echo ""

echo "💡 Exemplo de Implementação:"
echo "==========================="
echo "GET https://graph.facebook.com/v23.0/{wba-id}/phone_numbers"
echo "Headers: Authorization: Bearer {access_token}"
echo "Fields: id,phone_number,verified_name,quality_rating,code_verification_status,display_phone_number"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Phone Numbers API: https://developers.facebook.com/docs/whatsapp/phone-numbers"
echo "Graph API: https://developers.facebook.com/docs/graph-api"
echo ""

echo "💡 Próximos Passos:"
echo "=================="
echo "1. Implementar busca por números de telefone"
echo "2. Usar o endpoint correto da Meta API"
echo "3. Tratar casos onde não há números"
echo "4. Salvar números encontrados no banco"
