#!/bin/bash

echo "🧪 Testando Processo Completo do Config ID da Meta..."
echo "=================================================="

echo ""
echo "📋 Configurações atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "🎯 Processo Completo do Config ID:"
echo "================================="
echo "1. Frontend: Inicia Embedded Signup com Config ID"
echo "2. Facebook: Mostra processo de criação/seleção de conta WhatsApp Business"
echo "3. Usuário: Completa o processo de Embedded Signup"
echo "4. Facebook: Retorna código de autorização"
echo "5. Backend: Troca código por access token"
echo "6. Backend: Busca dados da conta WhatsApp Business criada"
echo ""

echo "🔍 Problema Identificado:"
echo "========================"
echo "❌ O Config ID está funcionando (recebemos código)"
echo "❌ O token exchange está funcionando"
echo "❌ Mas não há conta WhatsApp Business associada"
echo "❌ Isso indica que o processo de Embedded Signup não foi completado"
echo ""

echo "💡 Possíveis Causas:"
echo "==================="
echo "1. Config ID não está configurado para criar contas WhatsApp Business"
echo "2. Usuário não completou o processo de Embedded Signup"
echo "3. Permissões insuficientes para criar contas WhatsApp Business"
echo "4. Facebook App em modo de desenvolvimento"
echo "5. Domínio não autorizado no Config ID"
echo ""

echo "📱 Para Testar:"
echo "=============="
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Observe se aparece o processo de Embedded Signup"
echo "5. Verifique se consegue selecionar/criar conta WhatsApp Business"
echo "6. Complete todo o processo"
echo ""

echo "🔍 Logs para Observar:"
echo "====================="
echo "1. No console do navegador:"
echo "   - '📱 Mensagem do Facebook SDK: {type: 'WA_EMBEDDED_SIGNUP', event: 'FINISH'}'"
echo "   - '✅ Código de autorização recebido via Config ID'"
echo ""
echo "2. No backend:"
echo "   - '[META-AUTH] Iniciando troca de código por token...'"
echo "   - '[META-AUTH] ✅ Token trocado com sucesso SEM redirect_uri'"
echo "   - '[META-AUTH] INICIANDO BUSCA DE DADOS WHATSAPP BUSINESS'"
echo "   - '[META-AUTH] NENHUMA CONTA WHATSAPP BUSINESS ENCONTRADA'"
echo ""

echo "🚨 Se o Embedded Signup não aparecer:"
echo "===================================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se o domínio está autorizado"
echo "3. Verificar se as permissões estão concedidas"
echo "4. Verificar se o Facebook App está configurado corretamente"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo ""

echo "💡 Próximos Passos:"
echo "=================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se o processo de Embedded Signup aparece"
echo "3. Verificar se o usuário consegue completar o processo"
echo "4. Se necessário, criar novo Config ID"
echo "5. Verificar se o Facebook App está configurado corretamente"

