#!/bin/bash

echo "🧪 Validando Config ID da Meta..."
echo "================================"

echo ""
echo "📋 Configurações atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "🔍 Problema Identificado:"
echo "========================="
echo "❌ Config ID deveria permitir seleção/criação de conta WhatsApp Business"
echo "❌ Mas estamos recebendo 'conta não encontrada'"
echo "❌ Isso indica que o fluxo não está funcionando corretamente"
echo ""

echo "🎯 Possíveis Causas do Erro:"
echo "==========================="
echo "1. Config ID não está ativo no Facebook Developer Console"
echo "2. Config ID não está habilitado para Embedded Signup"
echo "3. Usuário não tem permissões para criar contas WhatsApp Business"
echo "4. Facebook App em modo de desenvolvimento"
echo "5. Domínio não autorizado no Config ID"
echo "6. Permissões insuficientes no Facebook App"
echo ""

echo "💡 Verificações Necessárias:"
echo "==========================="
echo "1. No Facebook Developer Console:"
echo "   - Acesse: https://developers.facebook.com/"
echo "   - Seu App > Produtos > WhatsApp Business API"
echo "   - Configurações > Cadastro incorporado"
echo "   - Verificar se o Config ID está 'Ativo'"
echo ""
echo "2. Verificar permissões do Facebook App:"
echo "   - whatsapp_business_management (OBRIGATÓRIO)"
echo "   - whatsapp_business_messaging (OBRIGATÓRIO)"
echo "   - business_management (OBRIGATÓRIO)"
echo ""
echo "3. Verificar se o usuário tem permissões:"
echo "   - Deve ter permissões para criar contas WhatsApp Business"
echo "   - Deve ser testador do Facebook App (se em modo desenvolvimento)"
echo ""

echo "🔧 Teste de Validação:"
echo "====================="
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Observe no console do navegador:"
echo "   - '📋 Configurações Facebook:'"
echo "   - '🚀 Iniciando login com Config ID:'"
echo "   - '📱 Resposta completa do Facebook:'"
echo "5. Verifique se o processo de Embedded Signup aparece"
echo "6. Verifique se consegue selecionar/criar conta WhatsApp Business"
echo ""

echo "🚨 Se o problema persistir:"
echo "=========================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se há restrições de domínio no Config ID"
echo "3. Verificar se o usuário tem permissões para usar o Config ID"
echo "4. Verificar se o Facebook App está em modo de desenvolvimento"
echo "5. Adicionar usuário como testador no Facebook App"
echo "6. Criar novo Config ID se necessário"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo ""

echo "📱 Próximos Passos:"
echo "=================="
echo "1. Verificar configuração do Config ID no Facebook Developer Console"
echo "2. Testar o fluxo completo e observar logs"
echo "3. Verificar se o processo de Embedded Signup aparece"
echo "4. Se não aparecer, verificar configurações do Facebook App"
echo "5. Se aparecer mas não funcionar, verificar permissões do usuário"

