#!/bin/bash

echo "🧪 Testando Busca da Conta WhatsApp Business..."
echo "=============================================="

echo ""
echo "📋 Informações da Conta:"
echo "======================="
echo "Nome da conta: Pandolfiz"
echo "ID da conta: 754286387300396"
echo "Proprietário: Gabriel Pandolfi"
echo ""

echo "🎯 Problema Identificado:"
echo "========================"
echo "✅ Conta WhatsApp Business existe no Meta Business Suite"
echo "✅ Conta está vinculada à sua conta de negócios"
echo "❌ Backend não consegue encontrar a conta via API"
echo ""

echo "🔍 Possíveis Causas:"
echo "==================="
echo "1. Permissões insuficientes no access token"
echo "2. Endpoint incorreto para buscar a conta"
echo "3. Token expirado ou inválido"
echo "4. Problema na estrutura da resposta da API"
echo ""

echo "📱 Para Testar:"
echo "=============="
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Complete o processo de Embedded Signup"
echo "5. Observe os logs do backend"
echo ""

echo "🔍 Logs Importantes para Observar:"
echo "================================="
echo "1. '[META-AUTH] Iniciando troca de código por token...'"
echo "2. '[META-AUTH] ✅ Token trocado com sucesso SEM redirect_uri'"
echo "3. '[META-AUTH] INICIANDO BUSCA DE DADOS WHATSAPP BUSINESS'"
echo "4. '[META-AUTH] Tentativa 1: Buscar WhatsApp Business do usuário diretamente'"
echo "5. '[META-AUTH] Resposta direta do WhatsApp Business: ...'"
echo "6. '[META-AUTH] Tentativa 2: Buscar todas as contas do usuário'"
echo "7. '[META-AUTH] Dados das contas: ...'"
echo ""

echo "💡 Se o problema persistir:"
echo "========================="
echo "1. Verificar se o access token tem as permissões corretas"
echo "2. Verificar se o endpoint está correto"
echo "3. Verificar se a estrutura da resposta está correta"
echo "4. Verificar se há erros específicos da API"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Graph API: https://developers.facebook.com/docs/graph-api"
echo ""

