#!/bin/bash

echo "🧪 Testando Fluxo de Embedded Signup..."
echo "======================================"

echo ""
echo "📋 Configurações atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "🎯 Problema Identificado:"
echo "========================"
echo "❌ Config ID está funcionando (recebemos código)"
echo "❌ Token exchange está funcionando"
echo "❌ Mas não há conta WhatsApp Business associada"
echo "❌ Isso indica que o Embedded Signup não criou/associou uma conta"
echo ""

echo "🔍 Possíveis Causas:"
echo "==================="
echo "1. Usuário não tem conta WhatsApp Business existente"
echo "2. Config ID não está configurado para criar contas"
echo "3. Processo de Embedded Signup não foi completado"
echo "4. Permissões insuficientes para criar contas"
echo "5. Facebook App em modo de desenvolvimento"
echo ""

echo "💡 Verificações Necessárias:"
echo "==========================="
echo "1. Durante o login, você viu o processo de Embedded Signup?"
echo "2. Apareceu uma tela para selecionar/criar conta WhatsApp Business?"
echo "3. Você conseguiu completar todo o processo?"
echo "4. Apareceu alguma mensagem de sucesso?"
echo ""

echo "🔧 Teste Manual:"
echo "==============="
echo "1. Acesse: https://localhost:5173"
echo "2. Vá para WhatsApp Credentials"
echo "3. Clique em 'Conectar com Facebook'"
echo "4. Observe se aparece o processo de Embedded Signup"
echo "5. Verifique se consegue selecionar/criar conta WhatsApp Business"
echo "6. Complete todo o processo"
echo ""

echo "📱 Logs para Observar:"
echo "====================="
echo "1. No console do navegador:"
echo "   - '📱 Mensagem do Facebook SDK: {type: 'WA_EMBEDDED_SIGNUP', event: 'FINISH'}'"
echo "   - '✅ Código de autorização recebido via Config ID'"
echo ""
echo "2. No backend:"
echo "   - '[META-AUTH] INICIANDO BUSCA DE DADOS WHATSAPP BUSINESS'"
echo "   - '[META-AUTH] Testando X endpoints para encontrar WhatsApp Business...'"
echo "   - '[META-AUTH] NENHUMA CONTA WHATSAPP BUSINESS ENCONTRADA'"
echo ""

echo "🚨 Se o Embedded Signup não aparecer:"
echo "===================================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se o domínio está autorizado"
echo "3. Verificar se as permissões estão concedidas"
echo "4. Verificar se o Facebook App está configurado corretamente"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo ""

echo "📱 Próximos Passos:"
echo "=================="
echo "1. Testar o fluxo completo e observar se o Embedded Signup aparece"
echo "2. Se não aparecer, verificar configurações do Facebook App"
echo "3. Se aparecer mas não funcionar, verificar permissões do usuário"
echo "4. Se necessário, criar novo Config ID"
echo "5. Verificar se o usuário tem permissões para criar contas WhatsApp Business"

