#!/bin/bash

echo "🔍 Verificando Fluxo do Config ID da Meta..."
echo "==========================================="

echo ""
echo "📋 Configurações atuais:"
echo "========================"
echo "App ID: $(grep "META_APP_ID=" src/.env | cut -d'=' -f2)"
echo "Config ID: $(grep "META_APP_CONFIG_ID=" src/.env | cut -d'=' -f2)"
echo "Redirect URI: $(grep "META_REDIRECT_URI=" src/.env | cut -d'=' -f2)"
echo ""

echo "🎯 Fluxo Correto do Config ID (Baseado na Documentação da Meta):"
echo "================================================================"
echo "1. Frontend: window.FB.login com config_id"
echo "2. Facebook: Retorna código de autorização"
echo "3. Backend: Troca código por access token"
echo "4. Backend: Busca dados da conta WhatsApp Business"
echo ""

echo "🔍 Nossa Implementação Atual:"
echo "============================"
echo "✅ Frontend: Config ID implementado corretamente"
echo "✅ Facebook: Retorna código de autorização"
echo "✅ Backend: Troca código por token (sem redirect_uri)"
echo "❌ Backend: Não encontra conta WhatsApp Business"
echo ""

echo "💡 Problema Identificado:"
echo "========================"
echo "❌ O Config ID está funcionando (recebemos código)"
echo "❌ O token exchange está funcionando"
echo "❌ Mas não há conta WhatsApp Business associada"
echo "❌ Isso indica que o processo de Embedded Signup não foi completado"
echo ""

echo "🔧 Possíveis Causas:"
echo "==================="
echo "1. Config ID não está configurado para criar contas WhatsApp Business"
echo "2. Usuário não completou o processo de Embedded Signup"
echo "3. Permissões insuficientes para criar contas WhatsApp Business"
echo "4. Facebook App em modo de desenvolvimento"
echo "5. Domínio não autorizado no Config ID"
echo ""

echo "📱 Verificações Necessárias:"
echo "==========================="
echo "1. No Facebook Developer Console:"
echo "   - Config ID deve estar 'Ativo'"
echo "   - Domínio localhost deve estar autorizado"
echo "   - Permissões devem estar concedidas"
echo ""
echo "2. No processo de login:"
echo "   - Deve aparecer o processo de Embedded Signup"
echo "   - Deve permitir selecionar/criar conta WhatsApp Business"
echo "   - Deve ser completado com sucesso"
echo ""

echo "🔗 Links para Verificação:"
echo "========================="
echo "Facebook Developer Console: https://developers.facebook.com/"
echo "Meta Business Suite: https://business.facebook.com/wa/manage/accounts"
echo "WhatsApp Business API: https://developers.facebook.com/docs/whatsapp"
echo "Embedded Signup: https://developers.facebook.com/docs/whatsapp/embedded-signup"
echo ""

echo "💡 Próximos Passos:"
echo "=================="
echo "1. Verificar se o Config ID está ativo no Facebook Developer Console"
echo "2. Verificar se o processo de Embedded Signup aparece"
echo "3. Verificar se o usuário consegue completar o processo"
echo "4. Se necessário, criar novo Config ID"
echo "5. Verificar se o Facebook App está configurado corretamente"

